// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pins.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPin = `-- name: CreatePin :one
INSERT INTO pins (id, created_at, updated_at, image_url, title, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, image_url, title, user_id
`

type CreatePinParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ImageUrl  string
	Title     string
	UserID    uuid.UUID
}

func (q *Queries) CreatePin(ctx context.Context, arg CreatePinParams) (Pin, error) {
	row := q.db.QueryRowContext(ctx, createPin,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ImageUrl,
		arg.Title,
		arg.UserID,
	)
	var i Pin
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.Title,
		&i.UserID,
	)
	return i, err
}

const deletePin = `-- name: DeletePin :exec
DELETE FROM pins WHERE id = $1 AND user_id = $2
`

type DeletePinParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePin(ctx context.Context, arg DeletePinParams) error {
	_, err := q.db.ExecContext(ctx, deletePin, arg.ID, arg.UserID)
	return err
}

const getPin = `-- name: GetPin :one
SELECT id, created_at, updated_at, image_url, title, user_id FROM pins WHERE id = $1
`

func (q *Queries) GetPin(ctx context.Context, id uuid.UUID) (Pin, error) {
	row := q.db.QueryRowContext(ctx, getPin, id)
	var i Pin
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.Title,
		&i.UserID,
	)
	return i, err
}

const getPinsByUserID = `-- name: GetPinsByUserID :many
SELECT id, created_at, updated_at, image_url, title, user_id FROM pins WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetPinsByUserID(ctx context.Context, userID uuid.UUID) ([]Pin, error) {
	rows, err := q.db.QueryContext(ctx, getPinsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pin
	for rows.Next() {
		var i Pin
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
			&i.Title,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
